package io.jenkins.plugins.checks.api;

import org.junit.jupiter.api.Test;

import static io.jenkins.plugins.checks.api.ChecksImageAssert.*;

class ChecksImageTest {
    @Test
    void shouldConstructCorrectly() {
        final String alt = "warnings-chart";
        final String imageUrl = "https://ci.jenkins.io/job/Plugins/job/warnings-ng-plugin/job/master/";
        final String caption = "charts generated by warning-ng-plugin";

        final ChecksImage image = new ChecksImage(alt, imageUrl);
        assertThat(image).hasAlt(alt).hasImageUrl(imageUrl);

        image.withCaption("charts generated by warning-ng-plugin");
        assertThat(image).hasCaption(caption);

        // test copy constructor
        final ChecksImage copied = new ChecksImage(image);
        assertThat(copied).hasAlt(alt).hasImageUrl(imageUrl).hasCaption(caption);
    }
}
