@startuml
|GitHub|
start
:New PR/Commit;
|Jenkins Instance|
:A job enters the queue;
|GitHub Checks API Plugin|
:Enumerate consumers to 
create check runs in "queued";
|GitHub|
:Create check runs;
stop

|Jenkins Instance|
start
:The related job starts;
|GitHub Checks API Plugin|
:Enumerate consumers to
update check runs to "in 
progress";
|GitHub|
:Update check runs;
stop

|Jenkins Instance|
start
:The related job completes;
|GitHub Checks API Plugin|
:Enumerate consumers to 
complete check runs with 
warnings, annotations, etc.;
|GitHub|
:Complete check runs
and display warnings,
annotations, etc.;
end
@enduml