@startuml

skinparam componentStyle uml2

component [codingstyle] #beige
component [github-checks-api] #lightGreen
component [github] #lightBlue
component [github-branch-source] #lightBlue
component [github-api] #lightBlue
component [jackson2-api] #lightBlue
component [plugin-util-api] #lightBlue

[github-checks-api] .up.> [codingstyle]
[github-checks-api] .left.> [plugin-util-api]
[github-checks-api] .right.> [jackson2-api]
[github-checks-api] ..> [github-branch-source]
[github-checks-api] ..> [github-api]
[github-checks-api] ..> [github]

[plugin-util-api] .up.> [codingstyle]
[github-branch-source] .> [github]
[github] ..> [github-api]
[github-branch-source] ..> [github-api]

skinparam legendBackgroundColor white
legend
|= |= Module type |
|<back:lightGreen>    </back>| GitHub Checks API Plugin |
|<back:lightBlue>    </back>| Jenkins Plugins |
|<back:beige>    </back>| Java Libraries |

endlegend

@enduml