name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    strategy:
      matrix:
        java: [21]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    name: on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn -Penable-jacoco clean verify -B -V -ntp

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        with:
          file: '*jacoco.xml'
